<<<<<<< HEAD
# Local defaults (overridden by Railway env vars)
spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/taskmanagerdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql@900}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007}
app.jwt.expiration=86400000

server.port=${PORT:8080}
=======
spring.datasource.url=jdbc:mysql://localhost:3306/taskmanagerdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mysql@900
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007
app.jwt.expiration=86400000

server.port=8080
spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:3000
>>>>>>> 9778d47e2ecea5b6ad6a962cef8299a81e65e66e
